export const qrAuctionV4Abi = [
  {
    inputs: [
      { internalType: "address", name: "_usdcToken", type: "address" },
      { internalType: "address", name: "_treasury", type: "address" },
      {
        internalType: "uint256",
        name: "_createBidReservePrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_contributeBidReservePrice",
        type: "uint256",
      },
      { internalType: "uint256", name: "_scheduledEndTime", type: "uint256" },
      { internalType: "string", name: "_urlString", type: "string" },
      { internalType: "uint256", name: "_validUntil", type: "uint256" },
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "AUCTION_ACTIVE", type: "error" },
  { inputs: [], name: "AUCTION_CREATE_FAILED_TO_LAUNCH", type: "error" },
  { inputs: [], name: "AUCTION_NOT_STARTED", type: "error" },
  { inputs: [], name: "AUCTION_OVER", type: "error" },
  { inputs: [], name: "AUCTION_SETTLED", type: "error" },
  { inputs: [], name: "BID_NOT_FOUND", type: "error" },
  { inputs: [], name: "EnforcedPause", type: "error" },
  { inputs: [], name: "ExpectedPause", type: "error" },
  { inputs: [], name: "INVALID_TOKEN_ID", type: "error" },
  { inputs: [], name: "NOT_WHITELISTED_SETTLER", type: "error" },
  {
    inputs: [{ internalType: "address", name: "owner", type: "address" }],
    name: "OwnableInvalidOwner",
    type: "error",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "OwnableUnauthorizedAccount",
    type: "error",
  },
  { inputs: [], name: "RESERVE_PRICE_NOT_MET", type: "error" },
  { inputs: [], name: "ReentrancyGuardReentrantCall", type: "error" },
  { inputs: [], name: "URL_ALREADY_HAS_BID", type: "error" },
  { inputs: [], name: "USDC_TOKEN_TRANSFER_FAILED", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "bidder",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "extended", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "urlString",
        type: "string",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
    ],
    name: "AuctionBid",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
    ],
    name: "AuctionCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct AuctionTypesV4.Bid",
        name: "winningBid",
        type: "tuple",
      },
    ],
    name: "AuctionSettled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct AuctionTypesV4.Bid",
        name: "originalWinner",
        type: "tuple",
      },
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        indexed: false,
        internalType: "struct AuctionTypesV4.Bid",
        name: "newWinner",
        type: "tuple",
      },
      { indexed: true, internalType: "bool", name: "refunded", type: "bool" },
    ],
    name: "AuctionWinnerOverridden",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "urlString",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "contributor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      { indexed: false, internalType: "bool", name: "extended", type: "bool" },
      {
        indexed: false,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      { indexed: false, internalType: "string", name: "name", type: "string" },
    ],
    name: "BidContributionMade",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "contributeBidReservePrice",
        type: "uint256",
      },
    ],
    name: "ContributeBidReservePriceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "createBidReservePrice",
        type: "uint256",
      },
    ],
    name: "CreateBidReservePriceUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "token",
        type: "address",
      },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "EmergencyWithdrawal",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "maxExtensionTime",
        type: "uint256",
      },
    ],
    name: "MaxExtensionTimeUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Paused",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "reason",
        type: "string",
      },
    ],
    name: "RefundFailed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "settler",
        type: "address",
      },
      { indexed: true, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "SettlerWhitelistUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "timeBuffer",
        type: "uint256",
      },
    ],
    name: "TimeBufferUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "Unpaused",
    type: "event",
  },
  {
    inputs: [],
    name: "auction",
    outputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        internalType: "struct AuctionTypesV4.Bid",
        name: "highestBid",
        type: "tuple",
      },
      { internalType: "uint256", name: "startTime", type: "uint256" },
      { internalType: "uint256", name: "endTime", type: "uint256" },
      { internalType: "bool", name: "settled", type: "bool" },
      {
        components: [
          { internalType: "uint256", name: "validUntil", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
        ],
        internalType: "struct AuctionTypesV4.QRData",
        name: "qrMetadata",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "contributeBidReservePrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "string", name: "_urlString", type: "string" },
      { internalType: "string", name: "_name", type: "string" },
    ],
    name: "contributeToBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_tokenId", type: "uint256" },
      { internalType: "string", name: "_urlString", type: "string" },
      { internalType: "string", name: "_name", type: "string" },
    ],
    name: "createBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "createBidReservePrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "emergencyWithdrawERC20",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllBids",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        internalType: "struct AuctionTypesV4.Bid[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "string", name: "_urlString", type: "string" }],
    name: "getBid",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "totalAmount", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
          {
            components: [
              { internalType: "address", name: "contributor", type: "address" },
              { internalType: "uint256", name: "amount", type: "uint256" },
              { internalType: "uint256", name: "timestamp", type: "uint256" },
            ],
            internalType: "struct AuctionTypesV4.BidContribution[]",
            name: "contributions",
            type: "tuple[]",
          },
        ],
        internalType: "struct AuctionTypesV4.Bid",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBidCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_bidder", type: "address" }],
    name: "getBidderName",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_settler", type: "address" }],
    name: "isWhitelistedSettler",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "maxExtensionTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_bidder", type: "address" },
      { internalType: "string", name: "_urlString", type: "string" },
      { internalType: "uint256", name: "_newAmount", type: "uint256" },
      { internalType: "bool", name: "_refundOriginalWinner", type: "bool" },
      { internalType: "string", name: "_name", type: "string" },
    ],
    name: "overrideAuctionWinner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "paused",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "scheduledEndTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_contributeBidReservePrice",
        type: "uint256",
      },
    ],
    name: "setContributeBidReservePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_createBidReservePrice",
        type: "uint256",
      },
    ],
    name: "setCreateBidReservePrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_urlString", type: "string" },
      { internalType: "uint256", name: "_validUntil", type: "uint256" },
    ],
    name: "setInitialMetadata",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_tokenId", type: "uint256" }],
    name: "setInitialTokenId",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_maxExtensionTime", type: "uint256" },
    ],
    name: "setMaxExtensionTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_scheduledEndTime", type: "uint256" },
    ],
    name: "setScheduledEndTime",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_timeBuffer", type: "uint256" }],
    name: "setTimeBuffer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_usdcToken", type: "address" }],
    name: "setUSDCToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "settings",
    outputs: [
      { internalType: "address", name: "usdcToken", type: "address" },
      { internalType: "address", name: "treasury", type: "address" },
      {
        internalType: "uint256",
        name: "createBidReservePrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "contributeBidReservePrice",
        type: "uint256",
      },
      { internalType: "uint256", name: "timeBuffer", type: "uint256" },
      { internalType: "bool", name: "launched", type: "bool" },
      { internalType: "uint256", name: "scheduledEndTime", type: "uint256" },
      { internalType: "uint256", name: "maxExtensionTime", type: "uint256" },
      {
        components: [
          { internalType: "uint256", name: "validUntil", type: "uint256" },
          { internalType: "string", name: "urlString", type: "string" },
        ],
        internalType: "struct AuctionTypesV4.QRData",
        name: "qrMetadata",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "settleAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "settleCurrentAndCreateNewAuction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "timeBuffer",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_settler", type: "address" },
      { internalType: "bool", name: "_status", type: "bool" },
    ],
    name: "updateSettlerWhitelist",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdcToken",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
